### ISSUE TITLE
[Bug] Random crash when evaluating pattern

### ISSUE THREAD

**Issue by LeagueRaINi** [WerWolv/ImHex#1934]
### Operating System

Windows

### What's the issue you encountered?

ImHex crashes when evaluating patterns seemingly at random on some of my firmware dumps

### How can the issue be reproduced?

Load firmware dump, load pattern and evaluate

### ImHex Version

1.35.4

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable

### Additional context?

Log: [20241016_032838.log](https://github.com/user-attachments/files/17387979/20241016_032838.log)
Pattern: [persistent_data_pattern.txt](https://github.com/user-attachments/files/17387981/persistent_data_pattern.txt)

Cant attach a dump of the firmware for legal reasons

**Comment by paxcut** [comment]
I understand not being able to post sensitive or otherwise restricted materials. In that case, one would invent an artificial file that is both not restricted and that exhibits the bug  when used as input for the pattern.  

I tried running the pattern on an input with all 0x44 zeroes and also used random values and nothing crashed. Does the file name have special characters in it? The pattern itself is fairly simple and I can't imagine anything in it being the cause but it is hard to tell without a reproducible case.

When you say 50/50 chance it will crash do you mean while it is evaluating the pattern or does it finish and then it crashes when you look at some data or something else? Also it is not clear if ImHex crashes when running the pattern in one particular file or on any valid file of the type. Form the log file it looks like you dont try to evaluate the pattern as it is crashing shortly after loading the layout. Maybe there is data corruption in initialization files. Try renaming them so they are recreated.

**Comment by paxcut** [comment]
@Husamdababneh  that may or may not be the same issue as the op reported. Your crash suggests that you are sorting the data as reported in issue #1938 , but the op doesn't mention sorting and doesn't provide a stack trace or ways to produce one.

**Comment by Husamdababneh** [comment]
@paxcut hmm, Acutally there is a log attached to the issue here  [20241016_032838.log](https://github.com/user-attachments/files/17387979/20241016_032838.log) with the same stack trace that I have as far as I can tell , I'm pretty sure that it's the same issue as #1938.

The issue is when you evaluate the pattern a call to `hex::ui::PatternDrawer::sortPatterns` method is invoked. 

Also, a proof of the issue (race condition) would be that when I try to evaluate the file and it succeed, sometimes the Pattern data window have different ordering

**Comment by paxcut** [comment]
I missed the fact that there was a log attached to the op, and from it it does indeed look like the same bug (I did say may or may nor though). So it looks like the race condition is related to both the evaluation and the sorting of the results. If you don't sort the results the crash doesn't seem to happen and just sorting results seems to work fine (although nothing seems to be changing which is kind of confusing)

**Comment by paxcut** [comment]
> Yes, not sorting the results does not crash, but the issue with pattern evaluation that it does the sorting automatically

What I meant is that if you don't sort the results you can evaluate the pattern as many times as you want without causing a crash, so even if evaluation sorts automatically that doesn't seem to create a problem unless you sort the data differently from the default sorting. Even if you sort away from default, the error only occurs when some data is accessed by two threads at the same time, or at least, that's my suspicion at the moment.

**Comment by LeagueRaINi** [comment]
Completely forgot to respond last time but yeah the sorting theory works out for me as well, after deleting all the configs the crashes are gone and last time they started I did indeed sort

**Comment by LeeTroy** [comment]
I'm seeing the same crash with windows portable 1.35.4 noGPU x86_64.
```
[10:29:50] [FATAL] [main | Main]               Received signal 'SIGSEGV' (11)
[10:29:50] [INFO]  [main | Main]               Wrote crash.json file to D:\Workspaces\imhex-1.35.4-Windows-Portable-NoGPU-x86_64\config\crash.json
[10:29:50] [FATAL] [main | Main]               Printing stacktrace using implementation 'StackWalk'
[10:29:50] [FATAL] [main | Main]                 (??) | ??
[10:29:50] [FATAL] [main | Main]                 (??) | ??
[10:29:50] [FATAL] [main | Main]                 (??) | ??
[10:29:50] [FATAL] [main | Main]                 (??) | ??
[10:29:50] [FATAL] [main | Main]                 (??) | ??
[10:29:50] [FATAL] [main | Main]                 (??) | _C_specific_handler
[10:29:50] [FATAL] [main | Main]                 (??) | _chkstk
[10:29:50] [FATAL] [main | Main]                 (??) | RtlFindCharInUnicodeString
[10:29:50] [FATAL] [main | Main]                 (??) | KiUserExceptionDispatcher
[10:29:50] [FATAL] [main | Main]                 (??) | hex::ui::PatternDrawer::sortPatterns(ImGuiTableSortSpecs const*, pl::ptrn::Pattern const*, pl::ptrn::Pattern const*) const
[10:29:50] [FATAL] [main | Main]                 (??) | void std::__insertion_sort<__gnu_cxx::__normal_iterator<pl::ptrn::Pattern**, std::vector<pl::ptrn::Pattern*, std::allocator<pl::ptrn::Pattern*>>>, __gnu_cxx::__ops::_Iter_comp_iter<std::function<bool (pl::ptrn::Pattern const*, pl::ptrn::Pattern const*)>>>(__gnu_cxx::__normal_iterator<pl::ptrn::Pattern**, std::vector<pl::ptrn::Pattern*, std::allocator<pl::ptrn::Pattern*>>>, __gnu_cxx::__normal_iterator<pl::ptrn::Pattern**, std::vector<pl::ptrn::Pattern*, std::allocator<pl::ptrn::Pattern*>>>, __gnu_cxx::__ops::_Iter_comp_iter<std::function<bool (pl::ptrn::Pattern const*, pl::ptrn::Pattern const*)>>)
[10:29:50] [FATAL] [main | Main]                 (??) | void std::__final_insertion_sort<__gnu_cxx::__normal_iterator<pl::ptrn::Pattern**, std::vector<pl::ptrn::Pattern*, std::allocator<pl::ptrn::Pattern*>>>, __gnu_cxx::__ops::_Iter_comp_iter<std::function<bool (pl::ptrn::Pattern const*, pl::ptrn::Pattern const*)>>>(__gnu_cxx::__normal_iterator<pl::ptrn::Pattern**, std::vector<pl::ptrn::Pattern*, std::allocator<pl::ptrn::Pattern*>>>, __gnu_cxx::__normal_iterator<pl::ptrn::Pattern**, std::vector<pl::ptrn::Pattern*, std::allocator<pl::ptrn::Pattern*>>>, __gnu_cxx::__ops::_Iter_comp_iter<std::function<bool (pl::ptrn::Pattern const*, pl::ptrn::Pattern const*)>>)
[10:29:50] [FATAL] [main | Main]                 (??) | pl::ptrn::PatternStruct::sort(std::function<bool (pl::ptrn::Pattern const*, pl::ptrn::Pattern const*)> const&)
[10:29:50] [FATAL] [main | Main]                 (??) | pl::ptrn::PatternStruct::sort(std::function<bool (pl::ptrn::Pattern const*, pl::ptrn::Pattern const*)> const&)
[10:29:50] [FATAL] [main | Main]                 (??) | hex::ui::PatternDrawer::beginPatternTable(std::vector<std::shared_ptr<pl::ptrn::Pattern>, std::allocator<std::shared_ptr<pl::ptrn::Pattern>>> const&, std::vector<pl::ptrn::Pattern*, std::allocator<pl::ptrn::Pattern*>>&, float) const
[10:29:50] [FATAL] [main | Main]                 (??) | hex::ui::PatternDrawer::draw(std::vector<std::shared_ptr<pl::ptrn::Pattern>, std::allocator<std::shared_ptr<pl::ptrn::Pattern>>> const&, pl::PatternLanguage const*, float)
[10:29:50] [FATAL] [main | Main]                 (??) | hex::plugin::builtin::ViewPatternData::drawContent()
[10:29:50] [FATAL] [main | Main]                 (??) | hex::View::Window::draw()
[10:29:50] [FATAL] [main | Main]                 (??) | ??
[10:29:50] [FATAL] [main | Main]                 (??) | ??
[10:29:50] [FATAL] [main | Main]                 (??) | ??
[10:29:50] [FATAL] [main | Main]                 (??) | ??
[10:29:50] [FATAL] [main | Main]                 (??) | ??
[10:29:50] [FATAL] [main | Main]                 (??) | ??
[10:29:50] [FATAL] [main | Main]                 (??) | BaseThreadInitThunk
[10:29:50] [FATAL] [main | Main]                 (??) | RtlUserThreadStart
[10:29:51] [INFO]  [main | Main]               Exit task 'Prepare exit' finished successfully
```

**Comment by paxcut** [comment]
The bug was fixed on the nightly builds. If you can't help running that version make sure you dont click the top column of the pattern data window which is what is used to sort the results. As long as you dont click that then the crashes you may experience will not be related to sorting.

**Comment by sonorousfreq** [comment]
Hi, 

I experience the same issue, can you point out when this fix will come into regular official builds and which exact version fixed this?
Also, it would be helpful to know what was the fix as well.

**Comment by paxcut** [comment]
I think this [commit ](https://github.com/WerWolv/ImHex/commit/3739bcc40c32087cfb0516ee9d0cc39256aa9cff) was made to help alleviate some of the issues that arise from sorting the value column of the pattern data window, but it has been found quite recently that there are still problems related to this issue. There is some additional information in this [issue](https://github.com/WerWolv/ImHex/issues/1938) about this problem. This [PR](https://github.com/WerWolv/ImHex/pull/2284) mentions fixing this problem in passing, but I couldn't make the connection between cloning and those long pointers to structs shown in the other issue. Recently all problems with `shared_from_this` were fixed and patterns can be cloned safely so it may be the right time to revisit this old bug once again.

To summarize and address your comments directly, the fix that was mentioned in this thread is the first link in this post above and was merged last December so it is already part of ImHex in all recent versions (1.36.*, 1.37.* and  1.38.*). The changes made there didn't fix the issue though and as of today there is no fix made that works in all cases. The only workaround is to avoid sorting the value column. Crashes could be prevented by simply not allowing the sorting to occur until a permanent fix is found. It is not even clear what does sorting of the values of the patterns actually means since the values in general cannot be compared. Why is the value column being sorted to begin with? What is the expected result of this operation and why is it worth putting up with ImHex crashing on the attempts?

**Comment by sonorousfreq** [comment]
Hi,

thanks for the prompt reply, on nightly I manged to download before download link stopped working, it seems to not crash for me (so far).

The pattern sorting, I am not sure what it does and I don't really use it explicitely, is this the sorter in Pattern Data window? Where one can sort table by column? If so, yes, if this is not stable, I would like to disable it, at least in official builds if possible.

The version I was using where it crashed frequently: v1.37.4.
The nightly that works fine: https://github.com/WerWolv/ImHex/commit/24732b304ba8c5ce1780c43d194c523992037558, v1.38.0.WIP.

If this was supposed to be fixed in 1.37.x I can provide some logs/crash dumps if needed, but seems pretty similar to usual pattern sorting crash.

**Comment by paxcut** [comment]
Download link still works find it here on github (see pic)or in werevolv.net at the bottom.

<img width="949" height="639" alt="Image" src="https://github.com/user-attachments/assets/a59b1e45-33a8-4c8c-a02d-9ae724959748" />

If I understand correctly what you claim is that the nightly build doesn't crash when running patterns on files that the previous version would crash on, but  you are not testing sorting so that problem may still exist and the one that was fixed was some other bug. 1.37.4 release has lots of problems and shouldn't be used. It is also over 5 months old so it is missing lots of features as well.
Until the next release is out nightlies should be the preferred choice. Thanks for testing things

**Comment by sonorousfreq** [comment]
Hi,

oh yes, the download llinks weren't working for us, for some reason (ours or yours server...) at the time.

I'll do more tests and report if I find something that still crashes it.

**Comment by paxcut** [comment]
It is possible for the download links to break. The builds can still be downloaded as artifacts that result from the entries you find in the github actions tab. Just follow the links from the build you want to test and you should find them. I can give detailed steps if you are still having trouble, but the artifacts will always be available as long as the build succeeds.
