### ISSUE TITLE
[Bug] Image visualizer displays noise for a loaded .bmp image.

### ISSUE THREAD

**Issue by clodoN1109** [WerWolv/ImHex#2081]
### Operating System

Windows

### What's the issue you encountered?

The image visualizer displays nonsensical output when reading a .bmp image. I've tested several files that work in ImHex previous version 1.35.4.

### How can the issue be reproduced?

Load a .bmp file. Set the image visualizer in the data processor and enter the run button.

![Image](https://github.com/user-attachments/assets/06f26b91-6e30-4fe3-b16d-875b332a59be)

Bellow I show the expected result, that is obtained with the same file and setting but in version 1.35.4.

![Image](https://github.com/user-attachments/assets/1ff2ecac-76d0-482a-9927-dc54230d26e1)

### ImHex Version

1.36.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

### Additional context?

I found the same problem in two different computers:

**Computer 1**
OS: Windows 11 Home Single Language 23H2
CPU: 12th Gen Intel(R) Core(TM) i7-12650H   2.30 GHz
GPU: GeForce RTX 3050

**Computer 2**
OS: Windows 11 Home Single Language 24H2
CPU: 12th Gen Intel(R) Core(TM) i7-12700H   2.30 GHz
GPU: GeForce RTX 3060

**Comment by WerWolv** [comment]
Hey! There was a bug in 1.36.2 that has been fixed since where the texture wasn't created correctly. You can use the latest nightly found on https://web.imhex.werwolv.net which should have the error fixed

**Comment by clodoN1109** [comment]
Hi! Thanks for your quick response!

Unfortunately, I just tested the same procedure on the web version, but it still didn’t work—no image appeared in the Image Visualizer. I tried it on Chrome (Windows 11) and Edge (Ubuntu 22.04), and the issue persists. The web version that appears to me is 1.37.0.
